build: false

environment:
  matrix:
    - PYTHON: C:\Miniconda-x64
    - PYTHON: C:\Miniconda36-x64

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv -y nose scikit-learn cython
  - activate testenv
  - python --version
  - python setup.py install

test_script:
  - nosetests -s -v gplearn

